//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentDetail
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string Image { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Status Status { get; set; }
    }
}
